spring:

  datasource:
    url: jdbc:mysql://localhost:3306/project?autoReconnect=true&useUnicode=true&CharSet=UTF-8&characterEncoding=UTF-8
    username: root
    password: dmi@123
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
