spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?autoReconnect=true&useUnicode=true&CharSet=UTF-8&characterEncoding=UTF-8
    username: root
    password: dmi@123
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 10
    max-idle: 4
    min-idle: 2
    test-while-idle:  true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis:  60000
    min-evictable-idle-time-millis: 300000

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
